# site settings
title: Rajnil Mukherjee
subtitle: The Aaevelion Project
email_1: rajnilmukherjee.rm@gmail.com
email_2: ms21213@iisermohali.ac.in
description: Welcome to my website!
baseurl: #the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Rajnil Mukherjee
street_address_1: F6/2 Indraloke Housing Estate 3, Paikpara
city_1: Kolkata
state_1: West Bengal
zip_code_1: 700002
country_1: India
phone_1: +91 8017965462
street_address_1: Hostel 5 Room 106, IISER Mohali, Sector 81 Knowledge City, PO Manauli
city_1: SAS Nagar (Mohali)
state_1: Punjab
zip_code_1: 140306
country_1: India
phone_1: +91 8017965462

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Aaevelion
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/rajnil_mukherjee/
  LinkedIn: https://www.linkedin.com/in/rajnil-mukherjee-503a5a1ba/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
